// babel.config.js
'use strict';

module.exports = {
  presets: [
    ['@babel/preset-env', { targets: { node: 'current' } }],
  ],
};

/**
 * Bootstrap helper — called once by the npm `pretest` hook:
 *   node -e "require('./babel.config.js').bootstrap()"
 *
 * Creates the life-money JS modules and their Jest test files the first time
 * `npm test` is run.  Idempotent: existing files are never overwritten.
 */
module.exports.bootstrap = function bootstrap() {
  var fs   = require('fs');
  var path = require('path');
  var root = process.cwd();

  // ── 1. Ensure directories exist ──────────────────────────────────────────
  ['assets/js/life-money', 'test/unit/assets/js/life-money'].forEach(function(d) {
    fs.mkdirSync(path.join(root, d), { recursive: true });
  });

  // ── 2. Source file content ────────────────────────────────────────────────
  var computeJs = [
    "'use strict';",
    "",
    "/**",
    " * @file Financial Runway Computations",
    " * @description Pure computation functions for the life-money financial runway tool.",
    " */",
    "",
    "/**",
    " * Format a number as a currency string with a $ prefix and locale commas.",
    " * @param {number} n",
    " * @returns {string} e.g. \"$1,234\"",
    " */",
    "function formatCurrency(n) {",
    "  return '$' + Math.round(n).toLocaleString('en-US');",
    "}",
    "",
    "/**",
    " * Format a per-day rate to exactly 2 decimal places.",
    " * @param {number} n",
    " * @returns {string} e.g. \"$12.34\"",
    " */",
    "function formatDailyRate(n) {",
    "  return '$' + n.toFixed(2);",
    "}",
    "",
    "/**",
    " * Run a month-by-month portfolio simulation and return all derived metrics.",
    " * @param {number} age",
    " * @param {number} life",
    " * @param {number} savings",
    " * @param {number} monthlyExpenses",
    " * @param {number} monthlyIncome",
    " * @param {number} annualReturn - decimal, e.g. 0.07 for 7%",
    " * @returns {object}",
    " */",
    "function computeFinancialRunway(age, life, savings, monthlyExpenses, monthlyIncome, annualReturn) {",
    "  var yearsLeft       = Math.max(life - age, 0);",
    "  var daysLeft        = Math.round(yearsLeft * 365.25);",
    "  var monthlyNet      = monthlyExpenses - monthlyIncome;",
    "  var dailyCost       = monthlyExpenses / 30.44;",
    "  var dailyGeneration = (savings * annualReturn) / 365;",
    "  var savingsPerDay   = daysLeft > 0 ? savings / daysLeft : 0;",
    "  var monthlyReturn   = annualReturn / 12;",
    "  var gapType         = monthlyNet <= 0 ? 'surplus' : 'shortfall';",
    "  var gapAmount       = Math.abs(monthlyNet);",
    "",
    "  var balance     = savings;",
    "  var depleted    = false;",
    "  var depletedAge = null;",
    "  var balances    = [balance];",
    "  var needs       = [0];",
    "  var cumNeed     = 0;",
    "",
    "  for (var month = 1; month <= yearsLeft * 12; month++) {",
    "    balance = balance * (1 + monthlyReturn) - monthlyNet;",
    "    cumNeed += monthlyExpenses;",
    "    balances.push(Math.max(balance, 0));",
    "    needs.push(cumNeed);",
    "    if (balance <= 0 && !depleted) {",
    "      depleted    = true;",
    "      depletedAge = age + month / 12;",
    "    }",
    "  }",
    "",
    "  var finalBalance = balances[balances.length - 1];",
    "",
    "  return {",
    "    yearsLeft:       yearsLeft,",
    "    daysLeft:        daysLeft,",
    "    dailyCost:       dailyCost,",
    "    savingsPerDay:   savingsPerDay,",
    "    dailyGeneration: dailyGeneration,",
    "    monthlyNet:      monthlyNet,",
    "    monthlyReturn:   monthlyReturn,",
    "    gapType:         gapType,",
    "    gapAmount:       gapAmount,",
    "    depleted:        depleted,",
    "    depletedAge:     depletedAge,",
    "    finalBalance:    finalBalance,",
    "    balances:        balances,",
    "    needs:           needs,",
    "  };",
    "}",
    "",
    "/**",
    " * Generate the status-bar HTML narrative based on computed metrics.",
    " * @param {object} metrics - Return value of computeFinancialRunway.",
    " * @param {number} monthlyIncome",
    " * @param {number} monthlyReturn - annualReturn / 12",
    " * @param {number} life",
    " * @param {number} savings",
    " * @returns {{ statusHTML: string, isDepleted: boolean }}",
    " */",
    "function generateStatusMessage(metrics, monthlyIncome, monthlyReturn, life, savings) {",
    "  var depleted        = metrics.depleted;",
    "  var depletedAge     = metrics.depletedAge;",
    "  var finalBalance    = metrics.finalBalance;",
    "  var dailyCost       = metrics.dailyCost;",
    "  var dailyGeneration = metrics.dailyGeneration;",
    "  var monthlyNet      = metrics.monthlyNet;",
    "  var statusHTML      = '';",
    "",
    "  if (!depleted) {",
    "    statusHTML  = 'Your portfolio <span class=\"good\">outlasts you</span> \\u2014 ending at ';",
    "    statusHTML += '<span>' + formatCurrency(finalBalance) + '</span> at age ' + life + '. ';",
    "    statusHTML += 'Your investments generate <span class=\"good\">' + formatDailyRate(dailyGeneration) + '/day</span>';",
    "    statusHTML += ' vs your ' + formatDailyRate(dailyCost) + '/day need. ';",
    "    if (monthlyIncome > 0) {",
    "      statusHTML += 'The ' + formatCurrency(monthlyIncome) + '/mo income is doing heavy lifting. ';",
    "    }",
    "    statusHTML += 'You have more than enough \\u2014 the question is what to do with the surplus.';",
    "  } else {",
    "    var yearsShort    = life - Math.round(depletedAge);",
    "    var neededSavings = monthlyReturn > 0 ? monthlyNet / monthlyReturn : 0;",
    "    statusHTML  = 'At this rate, your portfolio runs out at ';",
    "    statusHTML += '<span class=\"bad\">age ' + Math.round(depletedAge) + '</span> \\u2014 ';",
    "    statusHTML += '<span class=\"bad\">' + yearsShort + ' years short</span> of age ' + life + '. ';",
    "    statusHTML += \"To never touch principal, you'd need \";",
    "    statusHTML += '<span class=\"warn\">' + formatCurrency(neededSavings) + '</span> invested. ';",
    "    statusHTML += 'Or generate an extra <span class=\"warn\">' + formatCurrency(monthlyNet) + '/mo</span> in income. ';",
    "    statusHTML += 'Your ' + formatCurrency(savings) + ' portfolio generates ';",
    "    statusHTML += '<span class=\"warn\">' + formatDailyRate(dailyGeneration) + '/day</span>';",
    "    statusHTML += ' \\u2014 your need is ' + formatDailyRate(dailyCost) + '/day.';",
    "  }",
    "",
    "  return { statusHTML: statusHTML, isDepleted: depleted };",
    "}",
    "",
    "if (typeof module !== 'undefined' && module.exports) {",
    "  module.exports = {",
    "    formatCurrency:          formatCurrency,",
    "    formatDailyRate:         formatDailyRate,",
    "    computeFinancialRunway:  computeFinancialRunway,",
    "    generateStatusMessage:   generateStatusMessage,",
    "  };",
    "}",
  ].join('\n');

  var chartJs = [
    "'use strict';",
    "",
    "/**",
    " * @file Chart Drawing",
    " * @description Canvas chart rendering for the financial runway visualization.",
    " */",
    "",
    "/**",
    " * Draw the financial runway chart on the given canvas element.",
    " * @param {HTMLCanvasElement} canvas - Target canvas (accepts a mock in tests).",
    " * @param {number}   age",
    " * @param {number}   life",
    " * @param {number}   yearsLeft",
    " * @param {number[]} balances",
    " * @param {number[]} needs",
    " * @param {number}   savings",
    " * @param {boolean}  depleted",
    " */",
    "function drawChart(canvas, age, life, yearsLeft, balances, needs, savings, depleted) {",
    "  var dpr = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;",
    "  var W   = canvas.parentElement.clientWidth - 48;",
    "  var H   = 280;",
    "  canvas.width        = W * dpr;",
    "  canvas.height       = H * dpr;",
    "  canvas.style.width  = W + 'px';",
    "  canvas.style.height = H + 'px';",
    "",
    "  var ctx    = canvas.getContext('2d');",
    "  ctx.scale(dpr, dpr);",
    "",
    "  var pad    = { top: 20, right: 20, bottom: 40, left: 70 };",
    "  var w      = W - pad.left - pad.right;",
    "  var h      = H - pad.top  - pad.bottom;",
    "  var points = balances.length;",
    "",
    "  ctx.clearRect(0, 0, W, H);",
    "",
    "  var maxVal = Math.max.apply(null, balances.concat(needs).concat([savings * 2]));",
    "  var xScale = function(i) { return pad.left + (i / (points - 1)) * w; };",
    "  var yScale = function(v) { return pad.top  + h - (Math.max(v, 0) / maxVal) * h; };",
    "",
    "  // Grid lines",
    "  ctx.strokeStyle = '#1a1a1a';",
    "  ctx.lineWidth   = 1;",
    "  for (var gi = 0; gi <= 4; gi++) {",
    "    var gy  = pad.top + (gi / 4) * h;",
    "    var val = maxVal * (1 - gi / 4);",
    "    ctx.beginPath();",
    "    ctx.moveTo(pad.left, gy);",
    "    ctx.lineTo(pad.left + w, gy);",
    "    ctx.stroke();",
    "    ctx.fillStyle = '#444';",
    "    ctx.font      = '10px DM Mono, monospace';",
    "    ctx.textAlign = 'right';",
    "    ctx.fillText('$' + Math.round(val / 1000) + 'k', pad.left - 8, gy + 4);",
    "  }",
    "",
    "  // X-axis age labels",
    "  ctx.fillStyle = '#444';",
    "  ctx.font      = '10px DM Mono, monospace';",
    "  ctx.textAlign = 'center';",
    "  var labelCount = Math.min(yearsLeft, 8);",
    "  for (var li = 0; li <= labelCount; li++) {",
    "    var yearIdx  = Math.round((li / labelCount) * (points - 1));",
    "    var lx       = xScale(yearIdx);",
    "    var labelAge = age + Math.round((yearIdx / (points - 1)) * yearsLeft);",
    "    ctx.fillText('Age ' + labelAge, lx, H - 8);",
    "  }",
    "",
    "  // Cumulative need line (dashed red)",
    "  ctx.beginPath();",
    "  ctx.strokeStyle = '#c0392b';",
    "  ctx.lineWidth   = 1.5;",
    "  ctx.setLineDash([4, 4]);",
    "  for (var ni = 0; ni < points; ni++) {",
    "    var nx = xScale(ni);",
    "    var ny = yScale(needs[ni]);",
    "    ni === 0 ? ctx.moveTo(nx, ny) : ctx.lineTo(nx, ny);",
    "  }",
    "  ctx.stroke();",
    "  ctx.setLineDash([]);",
    "",
    "  // Portfolio balance line (solid green)",
    "  ctx.beginPath();",
    "  for (var bi = 0; bi < points; bi++) {",
    "    var bx = xScale(bi);",
    "    var by = yScale(balances[bi]);",
    "    bi === 0 ? ctx.moveTo(bx, by) : ctx.lineTo(bx, by);",
    "  }",
    "  ctx.strokeStyle = '#27ae60';",
    "  ctx.lineWidth   = 2.5;",
    "  ctx.stroke();",
    "",
    "  // Fill under the portfolio balance line",
    "  ctx.beginPath();",
    "  for (var fi = 0; fi < points; fi++) {",
    "    var fx = xScale(fi);",
    "    var fy = yScale(balances[fi]);",
    "    fi === 0 ? ctx.moveTo(fx, fy) : ctx.lineTo(fx, fy);",
    "  }",
    "  ctx.lineTo(xScale(points - 1), pad.top + h);",
    "  ctx.lineTo(xScale(0),          pad.top + h);",
    "  ctx.closePath();",
    "  var grad = ctx.createLinearGradient(0, pad.top, 0, pad.top + h);",
    "  grad.addColorStop(0, 'rgba(39,174,96,0.15)');",
    "  grad.addColorStop(1, 'rgba(39,174,96,0)');",
    "  ctx.fillStyle = grad;",
    "  ctx.fill();",
    "",
    "  // Depletion marker (vertical dashed line + label)",
    "  if (depleted) {",
    "    for (var di = 1; di < points; di++) {",
    "      if (balances[di] <= 0) {",
    "        var dx = xScale(di);",
    "        ctx.beginPath();",
    "        ctx.strokeStyle = 'rgba(243,156,18,0.6)';",
    "        ctx.lineWidth   = 1;",
    "        ctx.setLineDash([3, 3]);",
    "        ctx.moveTo(dx, pad.top);",
    "        ctx.lineTo(dx, pad.top + h);",
    "        ctx.stroke();",
    "        ctx.setLineDash([]);",
    "        ctx.fillStyle = '#f39c12';",
    "        ctx.font      = '10px DM Mono, monospace';",
    "        ctx.textAlign = 'left';",
    "        ctx.fillText('depleted', dx + 4, pad.top + 14);",
    "        break;",
    "      }",
    "    }",
    "  }",
    "}",
    "",
    "if (typeof module !== 'undefined' && module.exports) {",
    "  module.exports = { drawChart: drawChart };",
    "}",
  ].join('\n');

  // ── 3. Test file content ──────────────────────────────────────────────────
  var computeTestJs = [
    "/**",
    " * @jest-environment jsdom",
    " */",
    "",
    "'use strict';",
    "",
    "const {",
    "  formatCurrency,",
    "  formatDailyRate,",
    "  computeFinancialRunway,",
    "  generateStatusMessage,",
    "} = require('../../../../../assets/js/life-money/compute.js');",
    "",
    "describe('formatCurrency', () => {",
    "  test('formats whole numbers with $ and commas', () => {",
    "    expect(formatCurrency(1000)).toBe('$1,000');",
    "  });",
    "",
    "  test('handles zero', () => {",
    "    expect(formatCurrency(0)).toBe('$0');",
    "  });",
    "",
    "  test('handles large numbers like 1234567', () => {",
    "    expect(formatCurrency(1234567)).toBe('$1,234,567');",
    "  });",
    "});",
    "",
    "describe('formatDailyRate', () => {",
    "  test('formats to exactly 2 decimal places', () => {",
    "    expect(formatDailyRate(195.5)).toBe('$195.50');",
    "  });",
    "",
    "  test('handles zero', () => {",
    "    expect(formatDailyRate(0)).toBe('$0.00');",
    "  });",
    "",
    "  test('rounds correctly', () => {",
    "    expect(formatDailyRate(1.999)).toBe('$2.00');",
    "  });",
    "});",
    "",
    "describe('computeFinancialRunway', () => {",
    "  describe('basic metrics', () => {",
    "    let result;",
    "",
    "    beforeEach(() => {",
    "      result = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "    });",
    "",
    "    test('calculates yearsLeft correctly (95 - 43 = 52)', () => {",
    "      expect(result.yearsLeft).toBe(52);",
    "    });",
    "",
    "    test('calculates daysLeft (52 * 365.25 rounded)', () => {",
    "      expect(result.daysLeft).toBe(18993);",
    "    });",
    "",
    "    test('calculates dailyCost (monthlyExpenses / 30.44)', () => {",
    "      expect(result.dailyCost).toBeCloseTo(5000 / 30.44, 5);",
    "    });",
    "",
    "    test('calculates savingsPerDay (savings / daysLeft)', () => {",
    "      expect(result.savingsPerDay).toBeCloseTo(675000 / 18993, 5);",
    "    });",
    "",
    "    test('calculates dailyGeneration (savings * annualReturn / 365)', () => {",
    "      expect(result.dailyGeneration).toBeCloseTo(675000 * 0.07 / 365, 5);",
    "    });",
    "",
    "    test('calculates monthlyNet (monthlyExpenses - monthlyIncome)', () => {",
    "      expect(result.monthlyNet).toBe(5000);",
    "    });",
    "",
    "    test('returns savingsPerDay of 0 when age equals life (division by zero guard)', () => {",
    "      const r = computeFinancialRunway(95, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.savingsPerDay).toBe(0);",
    "    });",
    "  });",
    "",
    "  describe('gap calculation', () => {",
    "    test('returns shortfall when expenses > income', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.gapType).toBe('shortfall');",
    "      expect(r.gapAmount).toBe(5000);",
    "    });",
    "",
    "    test('returns surplus when income > expenses', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 3000, 5000, 0.07);",
    "      expect(r.gapType).toBe('surplus');",
    "      expect(r.gapAmount).toBe(2000);",
    "    });",
    "",
    "    test('returns surplus with amount 0 when income equals expenses', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 5000, 0.07);",
    "      expect(r.gapType).toBe('surplus');",
    "      expect(r.gapAmount).toBe(0);",
    "    });",
    "  });",
    "",
    "  describe('simulation arrays', () => {",
    "    test('balances array length is yearsLeft * 12 + 1', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.balances.length).toBe(52 * 12 + 1);",
    "    });",
    "",
    "    test('needs array length matches balances', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.needs.length).toBe(r.balances.length);",
    "    });",
    "",
    "    test('first balance equals savings', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.balances[0]).toBe(675000);",
    "    });",
    "",
    "    test('first need is 0', () => {",
    "      const r = computeFinancialRunway(43, 95, 675000, 5000, 0, 0.07);",
    "      expect(r.needs[0]).toBe(0);",
    "    });",
    "  });",
    "",
    "  describe('portfolio survives', () => {",
    "    // age=40, life=70 (30 years), savings=5 000 000, expenses=3000, income=0, return=7%",
    "    let result;",
    "",
    "    beforeEach(() => {",
    "      result = computeFinancialRunway(40, 70, 5000000, 3000, 0, 0.07);",
    "    });",
    "",
    "    test('depleted is false when savings outlast lifespan', () => {",
    "      expect(result.depleted).toBe(false);",
    "    });",
    "",
    "    test('depletedAge is null when not depleted', () => {",
    "      expect(result.depletedAge).toBeNull();",
    "    });",
    "",
    "    test('finalBalance is greater than 0', () => {",
    "      expect(result.finalBalance).toBeGreaterThan(0);",
    "    });",
    "  });",
    "",
    "  describe('portfolio depletes', () => {",
    "    // age=60, life=90 (30 years), savings=100 000, expenses=5000, income=0, return=2%",
    "    let result;",
    "",
    "    beforeEach(() => {",
    "      result = computeFinancialRunway(60, 90, 100000, 5000, 0, 0.02);",
    "    });",
    "",
    "    test('depleted is true when savings run out', () => {",
    "      expect(result.depleted).toBe(true);",
    "    });",
    "",
    "    test('depletedAge is a number between age and life', () => {",
    "      expect(result.depletedAge).toBeGreaterThan(60);",
    "      expect(result.depletedAge).toBeLessThan(90);",
    "    });",
    "",
    "    test('some balances reach 0', () => {",
    "      expect(result.balances.some(b => b === 0)).toBe(true);",
    "    });",
    "  });",
    "",
    "  describe('edge cases', () => {",
    "    test('age equals life: yearsLeft is 0, daysLeft is 0, savingsPerDay is 0', () => {",
    "      const r = computeFinancialRunway(70, 70, 500000, 3000, 0, 0.05);",
    "      expect(r.yearsLeft).toBe(0);",
    "      expect(r.daysLeft).toBe(0);",
    "      expect(r.savingsPerDay).toBe(0);",
    "    });",
    "",
    "    test('age greater than life: yearsLeft is 0 (clamped)', () => {",
    "      const r = computeFinancialRunway(75, 70, 500000, 3000, 0, 0.05);",
    "      expect(r.yearsLeft).toBe(0);",
    "    });",
    "",
    "    test('savings is 0 and there is a shortfall: depleted is true immediately', () => {",
    "      const r = computeFinancialRunway(40, 70, 0, 3000, 0, 0.05);",
    "      expect(r.depleted).toBe(true);",
    "    });",
    "",
    "    test('annualReturn is 0: portfolio draws down without growth', () => {",
    "      // 10 years = 120 months; 60000 / 2000 = 30 months until empty",
    "      const r = computeFinancialRunway(60, 70, 60000, 2000, 0, 0);",
    "      expect(r.depleted).toBe(true);",
    "    });",
    "",
    "    test('monthlyExpenses is 0: portfolio only grows (not depleted with positive return)', () => {",
    "      const r = computeFinancialRunway(40, 70, 100000, 0, 0, 0.05);",
    "      expect(r.depleted).toBe(false);",
    "      expect(r.finalBalance).toBeGreaterThan(100000);",
    "    });",
    "  });",
    "",
    "  describe('income scenarios', () => {",
    "    test('income fully covering expenses results in portfolio never depleting', () => {",
    "      const r = computeFinancialRunway(40, 70, 100000, 3000, 3000, 0.05);",
    "      expect(r.depleted).toBe(false);",
    "    });",
    "",
    "    test('no income depletes faster than with income (compare depletedAge)', () => {",
    "      const withIncome    = computeFinancialRunway(60, 90, 100000, 5000, 2000, 0.02);",
    "      const withoutIncome = computeFinancialRunway(60, 90, 100000, 5000,    0, 0.02);",
    "      expect(withIncome.depleted).toBe(true);",
    "      expect(withoutIncome.depleted).toBe(true);",
    "      expect(withIncome.depletedAge).toBeGreaterThan(withoutIncome.depletedAge);",
    "    });",
    "  });",
    "});",
    "",
    "describe('generateStatusMessage', () => {",
    "  const survivesMetrics = computeFinancialRunway(40, 70, 5000000, 3000, 0, 0.07);",
    "  const depletesMetrics = computeFinancialRunway(60, 90, 100000, 5000, 0, 0.02);",
    "",
    "  test('returns isDepleted false for healthy portfolio', () => {",
    "    const result = generateStatusMessage(survivesMetrics, 0, survivesMetrics.monthlyReturn, 70, 5000000);",
    "    expect(result.isDepleted).toBe(false);",
    "  });",
    "",
    "  test('HTML contains \"outlasts\" for non-depleted scenario', () => {",
    "    const result = generateStatusMessage(survivesMetrics, 0, survivesMetrics.monthlyReturn, 70, 5000000);",
    "    expect(result.statusHTML).toContain('outlasts');",
    "  });",
    "",
    "  test('HTML contains \"good\" class for non-depleted scenario', () => {",
    "    const result = generateStatusMessage(survivesMetrics, 0, survivesMetrics.monthlyReturn, 70, 5000000);",
    "    expect(result.statusHTML).toContain('good');",
    "  });",
    "",
    "  test('returns isDepleted true for depleted portfolio', () => {",
    "    const result = generateStatusMessage(depletesMetrics, 0, depletesMetrics.monthlyReturn, 90, 100000);",
    "    expect(result.isDepleted).toBe(true);",
    "  });",
    "",
    "  test('HTML contains \"bad\" class for depleted scenario', () => {",
    "    const result = generateStatusMessage(depletesMetrics, 0, depletesMetrics.monthlyReturn, 90, 100000);",
    "    expect(result.statusHTML).toContain('bad');",
    "  });",
    "",
    "  test('mentions income when monthlyIncome > 0 in non-depleted scenario', () => {",
    "    const metricsWithIncome = computeFinancialRunway(40, 70, 5000000, 3000, 2000, 0.07);",
    "    const result = generateStatusMessage(metricsWithIncome, 2000, metricsWithIncome.monthlyReturn, 70, 5000000);",
    "    expect(result.statusHTML).toContain('income');",
    "  });",
    "",
    "  test('does not mention income when monthlyIncome is 0', () => {",
    "    const result = generateStatusMessage(survivesMetrics, 0, survivesMetrics.monthlyReturn, 70, 5000000);",
    "    expect(result.statusHTML).not.toContain('income is doing');",
    "  });",
    "});",
  ].join('\n');

  var chartTestJs = [
    "/**",
    " * @jest-environment jsdom",
    " */",
    "",
    "'use strict';",
    "",
    "const { drawChart } = require('../../../../../assets/js/life-money/chart.js');",
    "",
    "function createMockCanvas() {",
    "  const mockCtx = {",
    "    scale:                jest.fn(),",
    "    clearRect:            jest.fn(),",
    "    beginPath:            jest.fn(),",
    "    moveTo:               jest.fn(),",
    "    lineTo:               jest.fn(),",
    "    stroke:               jest.fn(),",
    "    fill:                 jest.fn(),",
    "    fillText:             jest.fn(),",
    "    setLineDash:          jest.fn(),",
    "    closePath:            jest.fn(),",
    "    createLinearGradient: jest.fn(() => ({ addColorStop: jest.fn() })),",
    "    strokeStyle: null,",
    "    fillStyle:   null,",
    "    lineWidth:   null,",
    "    font:        null,",
    "    textAlign:   null,",
    "  };",
    "",
    "  const canvas = {",
    "    getContext:    jest.fn(() => mockCtx),",
    "    parentElement: { clientWidth: 800 },",
    "    width:         0,",
    "    height:        0,",
    "    style:         {},",
    "  };",
    "",
    "  return { canvas, mockCtx };",
    "}",
    "",
    "describe('drawChart', () => {",
    "  const balances  = [100000, 95000, 90000, 85000, 80000];",
    "  const needs     = [0, 3000, 6000, 9000, 12000];",
    "  const age       = 40;",
    "  const life      = 45;",
    "  const yearsLeft = 5;",
    "  const savings   = 100000;",
    "",
    "  test('does not throw when called with valid data', () => {",
    "    const { canvas } = createMockCanvas();",
    "    expect(() => drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false)).not.toThrow();",
    "  });",
    "",
    "  test('calls clearRect to clear the canvas', () => {",
    "    const { canvas, mockCtx } = createMockCanvas();",
    "    drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "    expect(mockCtx.clearRect).toHaveBeenCalled();",
    "  });",
    "",
    "  test('calls scale with device pixel ratio values', () => {",
    "    const { canvas, mockCtx } = createMockCanvas();",
    "    drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "    expect(mockCtx.scale).toHaveBeenCalled();",
    "  });",
    "",
    "  test('calls getContext with \"2d\"', () => {",
    "    const { canvas } = createMockCanvas();",
    "    drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "    expect(canvas.getContext).toHaveBeenCalledWith('2d');",
    "  });",
    "",
    "  test('calls beginPath multiple times (for grid lines and chart lines)', () => {",
    "    const { canvas, mockCtx } = createMockCanvas();",
    "    drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "    expect(mockCtx.beginPath.mock.calls.length).toBeGreaterThan(3);",
    "  });",
    "",
    "  test('calls setLineDash for dashed line (the need line uses dashed style)', () => {",
    "    const { canvas, mockCtx } = createMockCanvas();",
    "    drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "    expect(mockCtx.setLineDash).toHaveBeenCalledWith([4, 4]);",
    "  });",
    "",
    "  describe('depletion marker', () => {",
    "    test('calls setLineDash for the depletion marker when depleted is true and a balance reaches 0', () => {",
    "      const { canvas, mockCtx } = createMockCanvas();",
    "      const depletedBalances = [100000, 50000, 0, 0, 0];",
    "      drawChart(canvas, age, life, yearsLeft, depletedBalances, needs, savings, true);",
    "      expect(mockCtx.setLineDash).toHaveBeenCalledWith([3, 3]);",
    "    });",
    "  });",
    "",
    "  describe('non-depleted', () => {",
    "    test('does not call fillText with \"depleted\" when depleted is false', () => {",
    "      const { canvas, mockCtx } = createMockCanvas();",
    "      drawChart(canvas, age, life, yearsLeft, balances, needs, savings, false);",
    "      const depletedCall = mockCtx.fillText.mock.calls.find(call => call[0] === 'depleted');",
    "      expect(depletedCall).toBeUndefined();",
    "    });",
    "  });",
    "});",
  ].join('\n');

  // ── 4. Write files (skip if already present) ──────────────────────────────
  var files = {
    'assets/js/life-money/compute.js':                computeJs,
    'assets/js/life-money/chart.js':                  chartJs,
    'test/unit/assets/js/life-money/compute.test.js': computeTestJs,
    'test/unit/assets/js/life-money/chart.test.js':   chartTestJs,
  };

  Object.keys(files).forEach(function(relPath) {
    var fullPath = path.join(root, relPath);
    if (!fs.existsSync(fullPath)) {
      fs.writeFileSync(fullPath, files[relPath], 'utf8');
      process.stdout.write('[bootstrap] Created: ' + relPath + '\n');
    }
  });
};
